=== Fliskey/xmu/XML/实验3/SpyBase2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="spyREFType">
		<xs:restriction base="xs:string">
			<xs:pattern value="A[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--mIDType-->
	<xs:simpleType name="mIDType">
		<xs:restriction base="xs:string">
			<xs:pattern value="M[0-9]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<!--statusType-->
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Mission Accomplished"/>
			<xs:enumeration value="In Progress"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="spyTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="spyRow" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="firstName" type="xs:string"/>
							<xs:element name="lastName" type="xs:string"/>
							<xs:element name="aliasRow" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="alias" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="aID" type="xs:integer"/>
								</xs:complexType>
							</xs:element>
							<xs:element name="missionRow" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="date" type="xs:date"/>
										<xs:element name="description" type="xs:string"/>
										<xs:element name="status" type="statusType"/>
									</xs:sequence>
									<xs:attribute name="mID" type="mIDType"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="spyID" type="spyREFType"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Fliskey/xmu/XML/实验3/SpyBase2.xml
<?xml version="1.0" encoding="UTF-8"?>
<spyTable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SpyBase2.xsd">
	<spyRow spyID="A001">
		<firstName>Nikki</firstName>
		<lastName>Devgood</lastName>
		<aliasRow aID="1">
			<alias>Spy Grrrl</alias>
		</aliasRow>
		<aliasRow aID="2">
			<alias>La Femme Nikki</alias>
		</aliasRow>
		<missionRow mID="M101">
			<date>2005-04-15</date>
			<description>Crack the code</description>
			<status>Mission Accomplished</status>
		</missionRow>
		<missionRow mID="M102">
			<date>2006-02-15</date>
			<description>Get the source</description>
			<status>Mission Accomplished</status>
		</missionRow>
		<missionRow mID="M103">
			<date>2006-05-04</date>
			<description>Hit the target</description>
			<status>In Progress</status>
		</missionRow>
	</spyRow>
	<spyRow spyID="A006">
		<firstName>Link</firstName>
		<lastName>Lister</lastName>
		<aliasRow aID="3">
			<alias>LL</alias>
		</aliasRow>
		<aliasRow aID="4">
			<alias>Fred</alias>
		</aliasRow>
		<missionRow mID="M104">
			<date>2006-06-15</date>
			<description>Shoot the rapid</description>
			<status>In Progress</status>
		</missionRow>
	</spyRow>
	<spyRow spyID="A003">
		<firstName>Danger</firstName>
		<lastName>Mause</lastName>
		<aliasRow aID="5">
			<alias>Big Ears</alias>
		</aliasRow>
		<missionRow mID="M105">
			<date>2005-11-04</date>
			<description>Get the big cheese</description>
			<status>In Progress</status>
		</missionRow>
		<missionRow mID="M106">
			<date>2006-04-04</date>
			<description>Map the area</description>
			<status>In Progress</status>
		</missionRow>
	</spyRow>
	<spyRow spyID="A099">
		<firstName>Barbara</firstName>
		<lastName>Feldon</lastName>
		<missionRow mID="M107">
			<date>2006-05-02</date>
			<description>Get Smart</description>
			<status>In Progress</status>
		</missionRow>
	</spyRow>
	<spyRow spyID="A004">
		<firstName>Maxwell</firstName>
		<lastName>Smart</lastName>
		<aliasRow aID="6">
			<alias>Inspector Gadget</alias>
		</aliasRow>
		<aliasRow aID="7">
			<alias>Don Adams</alias>
		</aliasRow>
		<missionRow mID="M108">
			<date>1967-02-15</date>
			<description>Protect Chief</description>
			<status>In Progress</status>
		</missionRow>
		<missionRow mID="M109">
			<date>2006-06-15</date>
			<description>Get some style</description>
			<status>Mission Accomplished</status>
		</missionRow>
	</spyRow>
</spyTable>
